# Generated by Django 4.1.2 on 2022-12-06 11:10

from django.db import migrations, models
import django.db.models.deletion
import locais.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Vazio', 'Vazio'), ('Médio', 'Médio'), ('Cheio', 'Cheio')], default='Vazio', max_length=5)),
                ('tomada', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=5)),
                ('ruido', models.CharField(choices=[('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto', 'Alto')], default='Baixo', max_length=5)),
                ('coberto', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=5)),
                ('grupo', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=5)),
                ('permissoes', models.CharField(choices=[('Permitido comida e água', 'Permitido comida e água'), ('Não é permitida a ingestão de alimentos', 'Não é permitida a ingestão de alimentos')], default='Permitido comida e água', max_length=50)),
                ('flexibilidade', models.CharField(choices=[('É permitido entrar de mochila', 'É permitido entrar de mochila'), ('É preciso guardar os pertences em armários', 'É preciso guardar os pertences em armários')], default='É permitido entrar de mochila', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'PESSIMO'), (2, 'RUIM'), (3, 'MEDIO'), (4, 'BOM'), (5, 'OTIMO')], default=locais.models.Avaliacao.TiposAval['MEDIO'])),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locais.local')),
            ],
        ),
    ]
